### ISSUE TITLE
🌱 Add support for Azure plugin RBACRoleRule

### ISSUE THREAD

**Issue by mattwelke** [validator-labs/validatorctl#111]
### Summary

This is a new rule in the Azure plugin. Add support for it like the current RBAC role, where users are prompted for non-repetitive information (e.g. principal) and provide file paths for repetitive information (e.g. the role assignments), where they are able to copy-paste data directly from Azure documentation (e.g. role definition API pages) into the files.

**Comment by TylerGillson** [comment]
Let's just completely deprecate the original RBAC rule please.

**Comment by mattwelke** [comment]
We ended up agreeing that the original "RBAC role" was sufficient for our needs (because it can verify that a security principal has required permissions at a required scope). We don't need this new rule.
