### ISSUE TITLE
🌱 Prompt for Azure cloud to connect to and pass it into the Azure plugin

### ISSUE THREAD

**Issue by TylerGillson** [validator-labs/validatorctl#165]
### Summary

We're adding support to the Azure plugin for Azure Government. It will be powered by an env var, and validatorctl isn't passing the necessary env var during installation.

Needs to be passed to the Helm chat.

We also need to export that env var during direct execution. See https://github.com/validator-labs/validatorctl/issues/164.

**Comment by mattwelke** [comment]
Requires https://github.com/validator-labs/validator-plugin-azure/issues/239 first.
