### ISSUE TITLE
🐛 Azure secret name not auto-populated during reconfigure

### ISSUE THREAD

**Issue by TylerGillson** [validator-labs/validatorctl#29]
### Description

You can use the -r option to “reconfigure” validator. It fills in things from the config file you specify and prompts you for what’s not present in it.

For one combination of inputs for the Azure plugin, this doesn’t work for the “Secret Name” prompt. It should be reading it from the file and filling it in to the prompt but it isn’t.

This is the combination of prompts that cause it to not read the value from the config file:

```
Use implicit Azure auth? [Y/n]: No

Create Azure credential secret? [Y/n]: No
```

For example, here’s where I entered in the name of the secret. And this was saved in a config file at the end:
![1](https://github.com/validator-labs/validatorctl/assets/1795270/e2c23529-dc83-430c-9ee5-5b1c6a0f0ca6)

Note that when you get to the step where it asks for the Azure credentials secret name, it won’t already have a value:
![2](https://github.com/validator-labs/validatorctl/assets/1795270/aee9cc41-f4b8-4ea6-a357-c653f403ad7c)

This is the value it should have read from the config file and used:
![3](https://github.com/validator-labs/validatorctl/assets/1795270/7762ae72-580a-4c43-9ddc-ed876c03b29f)

### Reproduction steps

```bash
Use your own kind cluster. Do not allow the validator CLI to create a new one for you. Ensure it has a validator namespace Ensure there is a secret in the validator namespace in the cluster you’re going to use with the keys AZURE_TENANT_ID, AZURE_CLIENT_ID, and AZURE_CLIENT_SECRET. This causes the CLI to allow you to continue when you specify the name of a preexisting secret to use when you get to that step (otherwise it will display an error saying the secret name you specified doesn’t exist).

Execute `validator install -o`. Fill in all requested details until you’ve configured validator with the Azure plugin. Do not use implicit auth. Do not allow it to create the Azure credential secret.

Run the CLI again, with `validator install --config-file <path> -r -o`, using that file as input. --config-file is to enable it to use the file you made in the previous step. -r is to enable it to prompt you for any required data that’s missing in the config file. -o is to cause it to output a new file at the end instead of applying it to your kind cluster.

Repeat the input as above.
```

### Environment

```bash
validator and/or plugin versions:
kubectl version:
kind version:
etc...
```

**Comment by mattwelke** [comment]
Tested whether this bug still exists and found that it doesn't exist anymore.

If I run `validatorctl install -o` while specifying the Azure creds secret name as "azure-creds-2", then run `validatorctl install -o /path/to/validator.yaml -r`, it prompts me for all of the info I entered when first creating the config file via the `install` command, including the name of the secret. The prompt for secret name is populated with "azure-creds-2". This may be because we've done a few refactors on the code base over the past few months since this bug was reported, and we may have fixed it while doing those refactors.
